### PR TITLE
Add various options

### PR DESCRIPTION
**Pull request by suhan-paradkar**
Option to download fewer than 10 papers when --scholar-pages=1..(not tested) (on issue #33 )
It also has those changes of the master branch ```NOT``` on the DEV branch..

### CODE REVIEW

**Comment by suhan-paradkar** [comment]
@ferru97 ,I guess it would be better to have PyPaperBot-dev and Pypaperbot-UI as a seperate python package.. wont it?

**Comment by suhan-paradkar** [comment]
Well... The above proxy options cannotbe implemented in systems without sem_open implementation.. so.. it has to be changed..

**Comment by ferru97** [comment]
> @ferru97 ,I guess it would be better to have PyPaperBot-dev and Pypaperbot-UI as a seperate python package.. wont it?

Yes, but for the moment I don't think to implement it, if you want you can obviously do it

**Comment by ferru97** [comment]
Are these changes you made tested?

**Comment by suhan-paradkar** [comment]
> Are these changes you made tested?

Scholar results option is tested amd works fine... Proxy option is yet to be tested...

**Comment by suhan-paradkar** [comment]
Well proxy option works now

**Comment by ferru97** [comment]
Perfect, thanks!

**Pull request merged**
